### PR TITLE
Shortener reworked

### PR DESCRIPTION
**Pull request by alex-pex**
See #7 (Unexpected alias for files)

With this pull request : alias are used only if source url starts with the alias.

### CODE REVIEW

**Comment by alex-pex** [comment]
You should also look at : https://github.com/ixth/node-shortify/commit/03a1be603282185a3e1adc0f07af954d68bcd6eb

Apparently your node dependency is too strict

**Comment by bodokaiser** [comment]
Thank you! Does the new version work on npm?

**Comment by alex-pex** [comment]
I don't know. I never published a npm package.
On PHP package (composer/packagist) you need either to tag a release or change something in your package definition.

I did a npm update on my project and did not receive the update.

**Comment by bodokaiser** [comment]
Did you update the version to 0.0.6 in package.json?

Should be published: https://www.npmjs.com/package/shortify

**Comment by alex-pex** [comment]
You're right, I forgot to update the version in my project package.json.
It works ! I can know set shortify({"/": __dirname+"/"}) to have package 
loaded from the root of my project without messing with slashes in url.

**Comment by bodokaiser** [comment]
Great and thank you for contributing! ;)

**Pull request merged**
